- hosts: all
  tasks:
  - name: install the latest version of Apache
    yum:
      name: 
        - httpd
        - wget
        - tree
      state: latest
  - name: install git
    yum:
      name: git
      state: latest
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: stopped
  - name: remove git
    yum:
      name: git
      state: absent